name: bed_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  loading_animations: ^2.2.0
  firebase_core: "^0.7.0"
  cloud_firestore: "^0.16.0+1"
  firebase_auth: "^0.20.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/logo_small.png